version: "3.8"

services:
  mysql:
    build:
      context: ./database
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword12
      MYSQL_DATABASE: todo_task_app
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "testUser",
          "-ptestPassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: todo-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - todo-network

volumes:
  mysql-data:

networks:
  todo-network:
    driver: bridge
